
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LibraryManagementSystem
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect